module.exports = {
  codingSidebar: [
      {
        type: "doc",
        id: "Master"
      },
   {
       type: "autogenerated",
       dirName: "GuideData"
   }
  ],
//   officialGuide: [
//     {
//       type: "doc",
//       id: "Master",
//     },
//     {
//       type: "category",
//       label: "Guide",
//       items: [
//         "officialGuide/Info",
//         "officialGuide/RequiredTools",
//         "officialGuide/ProjectSetup",
//         "officialGuide/BuildRun",
//         "officialGuide/FirstMod",
//         "officialGuide/Debugging",
//         "officialGuide/GameModding",
//         "officialGuide/FinalWords",
//       ],
//     },
//   ],
};
