module.exports = {
  mainSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },

    //Installation: ['InstallingMods', 'ModList'],
    //Coding: ['StationUIText', 'EditingQuests'],
    //Designers: ['MainDesign'],
    //Reference: ['ItemIDs', 'ModuleIDs', 'RecipeIDs', 'GUIDFields', 'ItemStacks', 'RecipeTimes', 'QuestOrder'],
  ],
};
