module.exports = {
    codingSidebar: [
        {
            type: "doc",
            id: "Master"
        },
        {
            type: "autogenerated",
            dirName: "GuideData"
        }
    ],
};