module.exports = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'docs/InstallingMods'
    },
    {
      type: 'doc',
      id: 'docs/ModList'
    }
    //Installation: ['InstallingMods', 'ModList'],
    //Coding: ['StationUIText', 'EditingQuests'],
    //Designers: ['MainDesign'],
    //Reference: ['ItemIDs', 'ModuleIDs', 'RecipeIDs', 'GUIDFields', 'ItemStacks', 'RecipeTimes', 'QuestOrder'],
  ],
  codingSidebar: [
    {
      type: "doc",
      id: "coding/Master"
    },
    {
      type: "autogenerated",
      dirName: "coding/Home"
    }
  ],
  unitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'unity'
    }
  ]
};
